### ISSUE TITLE
Don't manage to import deck cards with version 1.5.0

### ISSUE THREAD

**Issue by masterbouh** [spacemandev-git/fvtt-card-support#38]
I had the same issue that was pointed in #37
So I tried to remove my decks, uninstall the module and resinstall it
I  am no longer able to import my sdf file.

Here is a screen shot when I click on import SDF
![Capture d’écran 2020-09-04 à 13 22 27](https://user-images.githubusercontent.com/70193836/92234275-042f0080-eeb2-11ea-893d-51a8a3525199.png)

There are two buttons to import the deck and I don't know which one to select to import the zip. I tried both but none of them work for me. When I click on the first one, the folder of the deck is created but nothing inside

Here is the deck I tried to import
[deck_init_jpg.zip](https://github.com/spacemandev-git/fvtt-card-support/files/5174508/deck_init_jpg.zip)

**Comment by spacemandev-git** [comment]
Hi, I fixed it for 1.5.1

With SDF and Images import, there is now 1 additional file import, this is the default back of the image.

In the image you posted, the first image is the SDF, the second is a png/jpg/some image file that represents the back of the deck (this used to be random but users wanted to specify). If you don't don't have one, you can use the ones found in 

```modules/cardsupport/assets/```
