### ISSUE TITLE
Currently non-reproducible: Card Support largely non-functional in worlds created in 0.7.x and higher

### ISSUE THREAD

**Issue by Norc** [spacemandev-git/fvtt-card-support#49]
The following error appears in the console when trying to draw a card to hand in a clean 0.7.5 world:
![image](https://user-images.githubusercontent.com/64667579/96775702-e6f8b780-13b5-11eb-82b7-699a5206563f.png)

Worlds created in 0.6.6 or earlier seem to be unaffected by this issue, but more investigation is needed.

**Comment by kristianserrano** [comment]
Strangely, I didn't have this problem on my local 0.7.4 instance.

**Comment by Norc** [comment]
Kristian was unable to reproduce, downgrading my panic level until this can be investigated further.
