### ISSUE TITLE
SDF fails to import every time

### ISSUE THREAD

**Issue by sharkbruhaha** [spacemandev-git/fvtt-card-support#51]
![image](https://user-images.githubusercontent.com/44031572/97127091-16d5f100-170f-11eb-9429-b00439adf2b8.png)

I keep getting this when I try to import.
I can import your example zip, but if I extract it and then zip it back up then it fails.
It fails when I have a 1 line item 1 png deck and when I have many.

I am on 0.7.5, and the world has been around awhile.
Tested in a new world and it fails the same.

**Comment by sharkbruhaha** [comment]
Did confirm that the import of images into foundry does work for making a Deck, but the import of a zip file for SDF does not (other than your original example one for whatever reason)

**Comment by sharkbruhaha** [comment]
[new_54CardDeck.zip](https://github.com/spacemandev-git/fvtt-card-support/files/5469998/new_54CardDeck.zip)
Uploading example re-zip of your sample one. This does NOT work for me. (on 0.7.5)
The OG:
[OG_54CardDeck.zip](https://github.com/spacemandev-git/fvtt-card-support/files/5469999/OG_54CardDeck.zip)

**Comment by sharkbruhaha** [comment]
herp derp derp....
So was some confusion in the example. I had thought that you had zipped 
"54CardDeck" not "images" and "deck.yaml". So that was what was making my SDF imports fail. I was doing their parent dir containing the 2 items, instead of the 2 items.

Closing ticket now, but maybe clarify in the README/wiki just to make sure others don't derp like I did.

**Comment by jcolson** [comment]
wow ... WHY does this matter, just spent an exorbitant amount of time messing with this....
